DROP DATABASE IF EXISTS biblioteca;
CREATE DATABASE biblioteca CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE biblioteca;

CREATE TABLE categoria (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE libro (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  autor VARCHAR(200) NOT NULL,
  isbn VARCHAR(20) DEFAULT NULL,
  descripcion TEXT DEFAULT NULL,
  categoria_id BIGINT UNSIGNED NOT NULL,
  fecha_publicacion DATE DEFAULT NULL,
  disponible BOOLEAN NOT NULL DEFAULT TRUE,
  precio DECIMAL(10,2) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_libro_categoria (categoria_id),
  CONSTRAINT fk_libro_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE queja (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre_cliente VARCHAR(150) DEFAULT NULL,
  email VARCHAR(200) DEFAULT NULL,
  telefono VARCHAR(30) DEFAULT NULL,
  tipo ENUM('QUEJA','SUGERENCIA','CONSULTA') NOT NULL DEFAULT 'CONSULTA',
  asunto VARCHAR(200) DEFAULT NULL,
  mensaje TEXT NOT NULL,
  tratado BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
